@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 28 02:09:15 +0200 2021
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_ALU_behav -key {Behavioral:sim_1:Functional:tb_ALU} -tclbatch tb_ALU.tcl -view C:/Users/Anestman/Documents/VLSI_labs/project_3/tb_ALU_behav.wcfg -log simulate.log"
call xsim  tb_ALU_behav -key {Behavioral:sim_1:Functional:tb_ALU} -tclbatch tb_ALU.tcl -view C:/Users/Anestman/Documents/VLSI_labs/project_3/tb_ALU_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
